# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RoZttzBbHA65JNF-u1oqqQmdjBal4AoW
"""

A = 10
B = 20.78
C = int(A + B)
print(A,B,C)
print(type(A))
print(type(B))
print(type(C))