# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDtEwv08hQMSycXurwmRu67HCJr1O4EK
"""

A = int(input())
B = int(input())
print("X = ", A + B)

import math

raio = float(input())
pi = 3.14159
area = pi * (raio ** 2)

print(f"A={area:.4f}")

raio = float(input( ))
pi = 3.14159
area = pi * (raio ** 2)

print(f"A={area:.4f}")

A = float(input())
B = float(input())
C = float(input())

media = (A * 2 + B * 3 + C * 5) / (2 + 3 + 5)

print(f"MEDIA = {media:.1f}")

def imprimir_tabuleiro(tabuleiro):
    """Imprime o tabuleiro do Jogo da Velha."""
    for linha in tabuleiro:
        print("|".join(linha))
        print("-" * 5)

def verificar_vitoria(tabuleiro, jogador):
    """Verifica se o jogador atual venceu."""
    # Verifica linhas
    for linha in tabuleiro:
        if all([celula == jogador for celula in linha]):
            return True
    # Verifica colunas
    for coluna in range(3):
        if all([tabuleiro[linha][coluna] == jogador for linha in range(3)]):
            return True
    # Verifica diagonais
    if tabuleiro[0][0] == tabuleiro[1][1] == tabuleiro[2][2] == jogador:
        return True
    if tabuleiro[0][2] == tabuleiro[1][1] == tabuleiro[2][0] == jogador:
        return True
    return False

def verificar_empate(tabuleiro):
    """Verifica se o jogo deu empate."""
    for linha in tabuleiro:
        if any([celula == " " for celula in linha]):
            return False
    return True

def jogar_partida():
    """Joga uma única partida de Jogo da Velha."""
    tabuleiro = [[" " for _ in range(3)] for _ in range(3)]
    jogador_atual = "X"
    while True:
        imprimir_tabuleiro(tabuleiro)
        try:
            linha = int(input(f"Jogador {jogador_atual}, digite a linha (0-2): "))
            coluna = int(input(f"Jogador {jogador_atual}, digite a coluna (0-2): "))
            if 0 <= linha < 3 and 0 <= coluna < 3:
                if tabuleiro[linha][coluna] == " ":
                    tabuleiro[linha][coluna] = jogador_atual
                    if verificar_vitoria(tabuleiro, jogador_atual):
                        imprimir_tabuleiro(tabuleiro)
                        print(f"Jogador {jogador_atual} venceu!")
                        return jogador_atual
                    elif verificar_empate(tabuleiro):
                        imprimir_tabuleiro(tabuleiro)
                        print("É um empate!")
                        return "Empate"
                    else:
                        jogador_atual = "O" if jogador_atual == "X" else "X"
                else:
                    print("Essa posição já está ocupada. Tente novamente.")
            else:
                print("Entrada inválida. Linha e coluna devem estar entre 0 e 2.")
        except ValueError:
            print("Entrada inválida. Por favor, digite apenas números.")


def main():
    """Executa o loop principal do jogo com placar."""
    pontuacoes = {"X": 0, "O": 0, "Empate": 0}
    total_partidas = 0

    while True:
        total_partidas += 1
        resultado = jogar_partida()
        pontuacoes[resultado] += 1

        print("\n--- Placar ---")
        print(f"Partidas jogadas: {total_partidas}")
        print(f"Vitórias do Jogador X: {pontuacoes['X']}")
        print(f"Vitórias do Jogador O: {pontuacoes['O']}")
        print(f"Empates: {pontuacoes['Empate']}")
        print("--------------\n")

        while True:
            jogar_novamente = input("Jogar novamente? (sim/não): ").lower()
            if jogar_novamente in ["sim", "não"]:
                break
            else:
                print("Entrada inválida. Por favor, digite 'sim' ou 'não'.")

        if jogar_novamente == "não":
            break

if __name__ == "__main__":
    main()

