# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lKNDB_x3KcktwOLI6t6saj5bNa1AoF5
"""

import struct

def decoder():
    """Lê o arquivo binário e decodifica a senha para uma dada referência."""
    file_name = "passwords.bin"

    try:
        with open(file_name, 'rb') as f:
            num_passwords_data = f.read(struct.calcsize('i'))
            if not num_passwords_data:
                print("Arquivo de senhas vazio.")
                return

            num_passwords = struct.unpack('i', num_passwords_data)[0]

            passwords_dict = {}
            for _ in range(num_passwords):
                ref_len_data = f.read(struct.calcsize('i'))
                if not ref_len_data:
                    print("Erro ao ler o comprimento da referência.")
                    return
                ref_len = struct.unpack('i', ref_len_data)[0]
                reference = f.read(ref_len).decode('utf-8')

                pass_len_data = f.read(struct.calcsize('i'))
                if not pass_len_data:
                    print("Erro ao ler o comprimento da senha.")
                    return
                pass_len = struct.unpack('i', pass_len_data)[0]
                password = f.read(pass_len).decode('utf-8')

                passwords_dict[reference] = password

            reference_to_find = input("Digite a referência da senha que você quer encontrar: ")

            if reference_to_find in passwords_dict:
                print(f"A senha para '{reference_to_find}' é: {passwords_dict[reference_to_find]}")
            else:
                print(f"Referência '{reference_to_find}' não encontrada no arquivo.")

    except FileNotFoundError:
        print(f"Arquivo '{file_name}' não encontrado. Execute o codificador primeiro para criá-lo.")
    except Exception as e:
        print(f"Ocorreu um erro: {e}")

# Adiciona esta linha para chamar a função decoder
decoder()

import struct
import os

def coder():
    """Cria ou atualiza um arquivo binário e armazena referências e senhas codificadas."""
    file_name = "passwords.bin"

    # Read existing data first if file exists
    passwords_dict = {}
    if os.path.exists(file_name) and os.path.getsize(file_name) > 0:
        try:
            with open(file_name, 'rb') as f:
                num_passwords_data = f.read(struct.calcsize('i'))
                if num_passwords_data:
                    num_passwords = struct.unpack('i', num_passwords_data)[0]
                    for _ in range(num_passwords):
                        ref_len_data = f.read(struct.calcsize('i'))
                        if not ref_len_data: break # Handle potential read error
                        ref_len = struct.unpack('i', ref_len_data)[0]
                        reference = f.read(ref_len).decode('utf-8')

                        pass_len_data = f.read(struct.calcsize('i'))
                        if not pass_len_data: break # Handle potential read error
                        pass_len = struct.unpack('i', pass_len_data)[0]
                        password = f.read(pass_len).decode('utf-8')
                        passwords_dict[reference] = password
        except Exception as e:
            print(f"Erro ao ler o arquivo existente: {e}")
            passwords_dict = {} # Reset dictionary if read fails


    while True:
        try:
            num_passwords_to_add_str = input("Quantas novas senhas você quer adicionar? ")
            num_passwords_to_add = int(num_passwords_to_add_str)
            break
        except ValueError:
            print("Entrada inválida. Por favor, digite um número inteiro.")

    for _ in range(num_passwords_to_add):
        reference = input("Digite a referência (ex: Gmail, Yahoo): ")
        password = input("Digite a senha: ")
        passwords_dict[reference] = password

    # Write all passwords (existing + new) back to the file
    with open(file_name, 'wb') as f:
        f.write(struct.pack('i', len(passwords_dict))) # Store the total number of passwords

        for reference, password in passwords_dict.items():
            encoded_reference = reference.encode('utf-8')
            encoded_password = password.encode('utf-8')

            # Write the length of the reference and password, then the encoded data
            f.write(struct.pack('i', len(encoded_reference)))
            f.write(encoded_reference)
            f.write(struct.pack('i', len(encoded_password)))
            f.write(encoded_password)

    print(f"Senhas codificadas e armazenadas em '{file_name}'")


def decoder():
    """Lê o arquivo binário e decodifica a senha para uma dada referência."""
    file_name = "passwords.bin"

    try:
        with open(file_name, 'rb') as f:
            num_passwords_data = f.read(struct.calcsize('i'))
            if not num_passwords_data:
                print("Arquivo de senhas vazio.")
                return

            num_passwords = struct.unpack('i', num_passwords_data)[0]

            passwords_dict = {}
            for _ in range(num_passwords):
                ref_len_data = f.read(struct.calcsize('i'))
                if not ref_len_data:
                    print("Erro ao ler o comprimento da referência.")
                    return
                ref_len = struct.unpack('i', ref_len_data)[0]
                reference = f.read(ref_len).decode('utf-8')

                pass_len_data = f.read(struct.calcsize('i'))
                if not pass_len_data:
                    print("Erro ao ler o comprimento da senha.")
                    return
                pass_len = struct.unpack('i', pass_len_data)[0]
                password = f.read(pass_len).decode('utf-8')

                passwords_dict[reference] = password

            reference_to_find = input("Digite a referência da senha que você quer encontrar: ")

            if reference_to_find in passwords_dict:
                print(f"A senha para '{reference_to_find}' é: {passwords_dict[reference_to_find]}")
            else:
                print(f"Referência '{reference_to_find}' não encontrada no arquivo.")

    except FileNotFoundError:
        print(f"Arquivo '{file_name}' não encontrado. Execute a opção de codificar primeiro para criá-lo.")
    except Exception as e:
        print(f"Ocorreu um erro: {e}")

# Main program loop
while True:
    print("\nEscolha uma opção:")
    print("1 - Codificar (adicionar senhas)")
    print("2 - Decodificar (buscar senha)")
    print("3 - Sair")

    choice = input("Digite o número da opção: ")

    if choice == '1':
        coder()
    elif choice == '2':
        decoder()
    elif choice == '3':
        print("Saindo do programa.")
        break
    else:
        print("Opção inválida. Por favor, digite 1, 2 ou 3.")