# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmpUbvqxwSg3OEtO3PT65Kon6xujYzQz
"""

valores = input("entre com dois inteiros: ").split()
x = int(valores[0])
y = int (valores[1])
op = input ('Informe o operador(+, -, *, / ou **):')
if op == "+":
  resultado = x + y
elif op == "-":
  resultado = x - y
elif op == "*":
  resultado = x * y
elif op == "/":
  resultado = x / y
elif op == "**":
  resultado = x ** y
else:
  resultado = None

if resultado == None:
  print(op, ": Operador inválido!!")
else:
  print(f"O resultado é: ", x, op, y, "=" , resultado)

indice = 1
while indice <= 2:
  print(indice, end="")
  indice = indice + 1
  print ()