# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6wcZaBvaC1DxLWZVZPFNseTD2uAW-is
"""



print ("Olá, bem vindo ao mundo da programação Python")