# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STt3chlOuxWigmwjbjhawh0Qb4QNBj9T
"""

nome = input('Digite seu nome:  ')
telefone = input('Digite seu número de telefone:  ')
email = input('Digite seu email:  ')
textoDigitado = "Nome: %s, Telefone: %s, Email: %s" % (nome, telefone, email)
print(textoDigitado)

salada = input ()
def receita (ingredientes):
  ingredientes = ingredientes.split()
  alface = []

  for i in range(len(ingredientes)-1):
    for j in range(i+1, len(ingredientes)):
        if ingredientes[i] == ingredientes[j]:
           alface.append(ingredientes[j])

  return alface
saida = receita(salada)
print(f"A saída do programa é: {saida}")